// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grep_log.proto

package greplog

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GrepLine struct {
	Line                 string   `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrepLine) Reset()         { *m = GrepLine{} }
func (m *GrepLine) String() string { return proto.CompactTextString(m) }
func (*GrepLine) ProtoMessage()    {}
func (*GrepLine) Descriptor() ([]byte, []int) {
	return fileDescriptor_grep_log_b03703fff956891a, []int{0}
}
func (m *GrepLine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrepLine.Unmarshal(m, b)
}
func (m *GrepLine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrepLine.Marshal(b, m, deterministic)
}
func (dst *GrepLine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrepLine.Merge(dst, src)
}
func (m *GrepLine) XXX_Size() int {
	return xxx_messageInfo_GrepLine.Size(m)
}
func (m *GrepLine) XXX_DiscardUnknown() {
	xxx_messageInfo_GrepLine.DiscardUnknown(m)
}

var xxx_messageInfo_GrepLine proto.InternalMessageInfo

func (m *GrepLine) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

type Cmd struct {
	Cmd                  string   `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cmd) Reset()         { *m = Cmd{} }
func (m *Cmd) String() string { return proto.CompactTextString(m) }
func (*Cmd) ProtoMessage()    {}
func (*Cmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_grep_log_b03703fff956891a, []int{1}
}
func (m *Cmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cmd.Unmarshal(m, b)
}
func (m *Cmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cmd.Marshal(b, m, deterministic)
}
func (dst *Cmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cmd.Merge(dst, src)
}
func (m *Cmd) XXX_Size() int {
	return xxx_messageInfo_Cmd.Size(m)
}
func (m *Cmd) XXX_DiscardUnknown() {
	xxx_messageInfo_Cmd.DiscardUnknown(m)
}

var xxx_messageInfo_Cmd proto.InternalMessageInfo

func (m *Cmd) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func init() {
	proto.RegisterType((*GrepLine)(nil), "greplog.GrepLine")
	proto.RegisterType((*Cmd)(nil), "greplog.Cmd")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrepLogClient is the client API for GrepLog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrepLogClient interface {
	ReturnMatches(ctx context.Context, in *Cmd, opts ...grpc.CallOption) (GrepLog_ReturnMatchesClient, error)
}

type grepLogClient struct {
	cc *grpc.ClientConn
}

func NewGrepLogClient(cc *grpc.ClientConn) GrepLogClient {
	return &grepLogClient{cc}
}

func (c *grepLogClient) ReturnMatches(ctx context.Context, in *Cmd, opts ...grpc.CallOption) (GrepLog_ReturnMatchesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GrepLog_serviceDesc.Streams[0], "/greplog.GrepLog/ReturnMatches", opts...)
	if err != nil {
		return nil, err
	}
	x := &grepLogReturnMatchesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GrepLog_ReturnMatchesClient interface {
	Recv() (*GrepLine, error)
	grpc.ClientStream
}

type grepLogReturnMatchesClient struct {
	grpc.ClientStream
}

func (x *grepLogReturnMatchesClient) Recv() (*GrepLine, error) {
	m := new(GrepLine)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GrepLogServer is the server API for GrepLog service.
type GrepLogServer interface {
	ReturnMatches(*Cmd, GrepLog_ReturnMatchesServer) error
}

func RegisterGrepLogServer(s *grpc.Server, srv GrepLogServer) {
	s.RegisterService(&_GrepLog_serviceDesc, srv)
}

func _GrepLog_ReturnMatches_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Cmd)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GrepLogServer).ReturnMatches(m, &grepLogReturnMatchesServer{stream})
}

type GrepLog_ReturnMatchesServer interface {
	Send(*GrepLine) error
	grpc.ServerStream
}

type grepLogReturnMatchesServer struct {
	grpc.ServerStream
}

func (x *grepLogReturnMatchesServer) Send(m *GrepLine) error {
	return x.ServerStream.SendMsg(m)
}

var _GrepLog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greplog.GrepLog",
	HandlerType: (*GrepLogServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReturnMatches",
			Handler:       _GrepLog_ReturnMatches_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grep_log.proto",
}

func init() { proto.RegisterFile("grep_log.proto", fileDescriptor_grep_log_b03703fff956891a) }

var fileDescriptor_grep_log_b03703fff956891a = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x2f, 0x4a, 0x2d,
	0x88, 0xcf, 0xc9, 0x4f, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x07, 0xf1, 0x73, 0xf2,
	0xd3, 0x95, 0xe4, 0xb8, 0x38, 0xdc, 0x8b, 0x52, 0x0b, 0x7c, 0x32, 0xf3, 0x52, 0x85, 0x84, 0xb8,
	0x58, 0x72, 0x32, 0xf3, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x71,
	0x2e, 0x66, 0xe7, 0xdc, 0x14, 0x21, 0x01, 0x2e, 0xe6, 0xe4, 0xdc, 0x14, 0xa8, 0x0c, 0x88, 0x69,
	0x64, 0xcf, 0xc5, 0x0e, 0xd6, 0x98, 0x9f, 0x2e, 0x64, 0xc2, 0xc5, 0x1b, 0x94, 0x5a, 0x52, 0x5a,
	0x94, 0xe7, 0x9b, 0x58, 0x92, 0x9c, 0x91, 0x5a, 0x2c, 0xc4, 0xa3, 0x07, 0x35, 0x5e, 0xcf, 0x39,
	0x37, 0x45, 0x4a, 0x10, 0xce, 0x83, 0xd9, 0xa4, 0xc4, 0x60, 0xc0, 0x98, 0xc4, 0x06, 0x76, 0x89,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x1a, 0x76, 0xd2, 0x9b, 0x00, 0x00, 0x00,
}
