package cfg

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
)

/*
Autogenerated from https://mholt.github.io/json-to-go/
*/

type ConfigType struct {
	DefaultUDPPort int    `json:"defaultUdpPort"`
	DefaultTCPPort int    `json:"defaultTcpPort"`
	LogDir         string `json:"logDir"`
	SdfsDir        string `json:"sdfsDir"`
	GrepDir        string `json:"grepDir"`
	Memlist        struct {
		FailureTimeout   int `json:"failureTimeout"`
		NodeNumberToPing int `json:"nodeNumberToPing"`
		MultiSendNumber  int `json:"MultiSendNumber"`
		RingSize         int `json:"ringSize"`
	} `json:"memlist"`
	Addrs []struct {
		IP   string `json:"ip"`
		Port int    `json:"port"`
	} `json:"addrs"`
}

var Cfg ConfigType
var configFileName = "cfg.json"

func init() {
	fileContent, err := ioutil.ReadFile(configFileName)
	if err != nil {
		fmt.Println("Cannot read the config file")
		return
	}
	if err := json.Unmarshal(fileContent, &Cfg); err != nil {
		fmt.Println("Fail to parse the JSON config file")
		return
	}
	//fmt.Println("Successfully parsed the JSON config file")
}
