package cfg

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"os"
	"os/user"
)

/*
Autogenerated from https://mholt.github.io/json-to-go/
*/

type ConfigType struct {
	DefaultUDPPort int    `json:"defaultUdpPort"`
	DefaultTCPPort int    `json:"defaultTcpPort"`
	LogDir         string `json:"logDir"`
	SdfsDir        string `json:"sdfsDir"`
	GrepDir        string `json:"grepDir"`
	StreamDir      string `json:"streamDir"`
	Memlist        struct {
		FailureTimeout   int `json:"failureTimeout"`
		NodeNumberToPing int `json:"nodeNumberToPing"`
		MultiSendNumber  int `json:"MultiSendNumber"`
		RingSize         int `json:"ringSize"`
	} `json:"memlist"`
	Addrs []struct {
		IP   string `json:"ip"`
		Port int    `json:"port"`
	} `json:"addrs"`
}

var Cfg ConfigType
var configFileName = "cfg.json"

func init() {
	homeDir := func() string {
		usr, err := user.Current()
		if err != nil {
			return ""
		}
		return usr.HomeDir
	}()

	fileContent, err := ioutil.ReadFile(configFileName)
	if err != nil {
		wd, _ := os.Getwd()
		fmt.Println("didn't find the config file under current directory:", wd)
		fileContent, err = ioutil.ReadFile(homeDir + "/" + configFileName)
		if err != nil {
			fmt.Println("didn't find the config file under home directory:", homeDir)
			return
		}
	}
	if err := json.Unmarshal(fileContent, &Cfg); err != nil {
		fmt.Println("Fail to parse the JSON config file")
		return
	}
	//fmt.Println("Successfully parsed the JSON config file")
}
