// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server_services.proto

package serverservices

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConfigInfo struct {
	LogLevel             int32    `protobuf:"varint,1,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	VmIndex              int32    `protobuf:"varint,2,opt,name=vm_index,json=vmIndex,proto3" json:"vm_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigInfo) Reset()         { *m = ConfigInfo{} }
func (m *ConfigInfo) String() string { return proto.CompactTextString(m) }
func (*ConfigInfo) ProtoMessage()    {}
func (*ConfigInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8065473b34526ba4, []int{0}
}

func (m *ConfigInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigInfo.Unmarshal(m, b)
}
func (m *ConfigInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigInfo.Marshal(b, m, deterministic)
}
func (m *ConfigInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigInfo.Merge(m, src)
}
func (m *ConfigInfo) XXX_Size() int {
	return xxx_messageInfo_ConfigInfo.Size(m)
}
func (m *ConfigInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigInfo proto.InternalMessageInfo

func (m *ConfigInfo) GetLogLevel() int32 {
	if m != nil {
		return m.LogLevel
	}
	return 0
}

func (m *ConfigInfo) GetVmIndex() int32 {
	if m != nil {
		return m.VmIndex
	}
	return 0
}

type StringMessage struct {
	Mesg                 string   `protobuf:"bytes,1,opt,name=mesg,proto3" json:"mesg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringMessage) Reset()         { *m = StringMessage{} }
func (m *StringMessage) String() string { return proto.CompactTextString(m) }
func (*StringMessage) ProtoMessage()    {}
func (*StringMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8065473b34526ba4, []int{1}
}

func (m *StringMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMessage.Unmarshal(m, b)
}
func (m *StringMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMessage.Marshal(b, m, deterministic)
}
func (m *StringMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMessage.Merge(m, src)
}
func (m *StringMessage) XXX_Size() int {
	return xxx_messageInfo_StringMessage.Size(m)
}
func (m *StringMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StringMessage proto.InternalMessageInfo

func (m *StringMessage) GetMesg() string {
	if m != nil {
		return m.Mesg
	}
	return ""
}

type StringArray struct {
	Mesgs                []string `protobuf:"bytes,1,rep,name=mesgs,proto3" json:"mesgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringArray) Reset()         { *m = StringArray{} }
func (m *StringArray) String() string { return proto.CompactTextString(m) }
func (*StringArray) ProtoMessage()    {}
func (*StringArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_8065473b34526ba4, []int{2}
}

func (m *StringArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringArray.Unmarshal(m, b)
}
func (m *StringArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringArray.Marshal(b, m, deterministic)
}
func (m *StringArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringArray.Merge(m, src)
}
func (m *StringArray) XXX_Size() int {
	return xxx_messageInfo_StringArray.Size(m)
}
func (m *StringArray) XXX_DiscardUnknown() {
	xxx_messageInfo_StringArray.DiscardUnknown(m)
}

var xxx_messageInfo_StringArray proto.InternalMessageInfo

func (m *StringArray) GetMesgs() []string {
	if m != nil {
		return m.Mesgs
	}
	return nil
}

type IntMessage struct {
	Mesg                 int32    `protobuf:"varint,1,opt,name=mesg,proto3" json:"mesg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntMessage) Reset()         { *m = IntMessage{} }
func (m *IntMessage) String() string { return proto.CompactTextString(m) }
func (*IntMessage) ProtoMessage()    {}
func (*IntMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8065473b34526ba4, []int{3}
}

func (m *IntMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntMessage.Unmarshal(m, b)
}
func (m *IntMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntMessage.Marshal(b, m, deterministic)
}
func (m *IntMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntMessage.Merge(m, src)
}
func (m *IntMessage) XXX_Size() int {
	return xxx_messageInfo_IntMessage.Size(m)
}
func (m *IntMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_IntMessage.DiscardUnknown(m)
}

var xxx_messageInfo_IntMessage proto.InternalMessageInfo

func (m *IntMessage) GetMesg() int32 {
	if m != nil {
		return m.Mesg
	}
	return 0
}

type DetectorMessage struct {
	Header               string   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	SessNum              int32    `protobuf:"varint,3,opt,name=sess_num,json=sessNum,proto3" json:"sess_num,omitempty"`
	Ttl                  int32    `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetectorMessage) Reset()         { *m = DetectorMessage{} }
func (m *DetectorMessage) String() string { return proto.CompactTextString(m) }
func (*DetectorMessage) ProtoMessage()    {}
func (*DetectorMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8065473b34526ba4, []int{4}
}

func (m *DetectorMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectorMessage.Unmarshal(m, b)
}
func (m *DetectorMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectorMessage.Marshal(b, m, deterministic)
}
func (m *DetectorMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectorMessage.Merge(m, src)
}
func (m *DetectorMessage) XXX_Size() int {
	return xxx_messageInfo_DetectorMessage.Size(m)
}
func (m *DetectorMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectorMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DetectorMessage proto.InternalMessageInfo

func (m *DetectorMessage) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *DetectorMessage) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *DetectorMessage) GetSessNum() int32 {
	if m != nil {
		return m.SessNum
	}
	return 0
}

func (m *DetectorMessage) GetTtl() int32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

type Member struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	SessNum              int32    `protobuf:"varint,2,opt,name=sess_num,json=sessNum,proto3" json:"sess_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_8065473b34526ba4, []int{5}
}

func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Member) GetSessNum() int32 {
	if m != nil {
		return m.SessNum
	}
	return 0
}

type FullMembershipList struct {
	List                 []*Member `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FullMembershipList) Reset()         { *m = FullMembershipList{} }
func (m *FullMembershipList) String() string { return proto.CompactTextString(m) }
func (*FullMembershipList) ProtoMessage()    {}
func (*FullMembershipList) Descriptor() ([]byte, []int) {
	return fileDescriptor_8065473b34526ba4, []int{6}
}

func (m *FullMembershipList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FullMembershipList.Unmarshal(m, b)
}
func (m *FullMembershipList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FullMembershipList.Marshal(b, m, deterministic)
}
func (m *FullMembershipList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FullMembershipList.Merge(m, src)
}
func (m *FullMembershipList) XXX_Size() int {
	return xxx_messageInfo_FullMembershipList.Size(m)
}
func (m *FullMembershipList) XXX_DiscardUnknown() {
	xxx_messageInfo_FullMembershipList.DiscardUnknown(m)
}

var xxx_messageInfo_FullMembershipList proto.InternalMessageInfo

func (m *FullMembershipList) GetList() []*Member {
	if m != nil {
		return m.List
	}
	return nil
}

type UDPMessage struct {
	MessageType          string              `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Dm                   *DetectorMessage    `protobuf:"bytes,2,opt,name=dm,proto3" json:"dm,omitempty"`
	Fm                   *FullMembershipList `protobuf:"bytes,3,opt,name=fm,proto3" json:"fm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UDPMessage) Reset()         { *m = UDPMessage{} }
func (m *UDPMessage) String() string { return proto.CompactTextString(m) }
func (*UDPMessage) ProtoMessage()    {}
func (*UDPMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8065473b34526ba4, []int{7}
}

func (m *UDPMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UDPMessage.Unmarshal(m, b)
}
func (m *UDPMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UDPMessage.Marshal(b, m, deterministic)
}
func (m *UDPMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UDPMessage.Merge(m, src)
}
func (m *UDPMessage) XXX_Size() int {
	return xxx_messageInfo_UDPMessage.Size(m)
}
func (m *UDPMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UDPMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UDPMessage proto.InternalMessageInfo

func (m *UDPMessage) GetMessageType() string {
	if m != nil {
		return m.MessageType
	}
	return ""
}

func (m *UDPMessage) GetDm() *DetectorMessage {
	if m != nil {
		return m.Dm
	}
	return nil
}

func (m *UDPMessage) GetFm() *FullMembershipList {
	if m != nil {
		return m.Fm
	}
	return nil
}

func init() {
	proto.RegisterType((*ConfigInfo)(nil), "serverservices.ConfigInfo")
	proto.RegisterType((*StringMessage)(nil), "serverservices.StringMessage")
	proto.RegisterType((*StringArray)(nil), "serverservices.StringArray")
	proto.RegisterType((*IntMessage)(nil), "serverservices.IntMessage")
	proto.RegisterType((*DetectorMessage)(nil), "serverservices.DetectorMessage")
	proto.RegisterType((*Member)(nil), "serverservices.Member")
	proto.RegisterType((*FullMembershipList)(nil), "serverservices.FullMembershipList")
	proto.RegisterType((*UDPMessage)(nil), "serverservices.UDPMessage")
}

func init() { proto.RegisterFile("server_services.proto", fileDescriptor_8065473b34526ba4) }

var fileDescriptor_8065473b34526ba4 = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xce, 0x07, 0xcd, 0xb8, 0x29, 0x68, 0x04, 0x95, 0x69, 0x85, 0x08, 0xdb, 0x4b, 0xc5,
	0x21, 0x20, 0x73, 0xe0, 0x4a, 0xd5, 0x08, 0x29, 0xd0, 0x20, 0x70, 0xe0, 0x6c, 0xb9, 0xf1, 0xc4,
	0x31, 0xda, 0xb5, 0xa3, 0xdd, 0x4d, 0x44, 0xfe, 0x07, 0xff, 0x8a, 0x3f, 0x85, 0x76, 0xd7, 0x51,
	0x88, 0x5b, 0xc8, 0xc9, 0x33, 0x6f, 0xdf, 0x3c, 0xbf, 0x59, 0x3f, 0xc3, 0x53, 0x45, 0x72, 0x4d,
	0x32, 0x31, 0x8f, 0x62, 0x46, 0x6a, 0xb8, 0x94, 0x95, 0xae, 0xf0, 0xc4, 0xc1, 0x5b, 0x94, 0x8d,
	0x00, 0xae, 0xab, 0x72, 0x5e, 0xe4, 0xe3, 0x72, 0x5e, 0xe1, 0x39, 0xf4, 0x78, 0x95, 0x27, 0x9c,
	0xd6, 0xc4, 0x43, 0x6f, 0xe0, 0x5d, 0x76, 0xe2, 0x23, 0x5e, 0xe5, 0x37, 0xa6, 0xc7, 0x67, 0x70,
	0xb4, 0x16, 0x49, 0x51, 0x66, 0xf4, 0x33, 0xf4, 0xed, 0xd9, 0xc3, 0xb5, 0x18, 0x9b, 0x96, 0x5d,
	0x40, 0x7f, 0xaa, 0x65, 0x51, 0xe6, 0x13, 0x52, 0x2a, 0xcd, 0x09, 0x11, 0xda, 0x82, 0x54, 0x6e,
	0x35, 0x7a, 0xb1, 0xad, 0xd9, 0x05, 0x04, 0x8e, 0x74, 0x25, 0x65, 0xba, 0xc1, 0x27, 0xd0, 0x31,
	0xb0, 0x0a, 0xbd, 0x41, 0xeb, 0xb2, 0x17, 0xbb, 0x86, 0x0d, 0x00, 0xc6, 0xa5, 0xbe, 0x4f, 0xa6,
	0x53, 0xcb, 0xfc, 0x80, 0x47, 0x23, 0xd2, 0x34, 0xd3, 0x95, 0xdc, 0xd2, 0x4e, 0xa1, 0xbb, 0xa0,
	0x34, 0x23, 0x59, 0xbf, 0xaf, 0xee, 0xcc, 0x78, 0x9a, 0x65, 0xd2, 0xba, 0xed, 0xc5, 0xb6, 0x36,
	0x5b, 0x28, 0x52, 0x2a, 0x29, 0x57, 0x22, 0x6c, 0xb9, 0x2d, 0x4c, 0xff, 0x79, 0x25, 0xf0, 0x31,
	0xb4, 0xb4, 0xe6, 0x61, 0xdb, 0xa2, 0xa6, 0x64, 0xef, 0xa0, 0x3b, 0x21, 0x71, 0xfb, 0x97, 0x94,
	0xf7, 0x0f, 0x29, 0x7f, 0x4f, 0x8a, 0xbd, 0x07, 0xfc, 0xb0, 0xe2, 0xdc, 0x0d, 0xab, 0x45, 0xb1,
	0xbc, 0x29, 0x94, 0xc6, 0x57, 0xd0, 0xe6, 0x85, 0xd2, 0x76, 0xe3, 0x20, 0x3a, 0x1d, 0xee, 0x7f,
	0x8b, 0xa1, 0x63, 0xc7, 0x96, 0xc3, 0x7e, 0x79, 0x00, 0xdf, 0x47, 0x5f, 0xb6, 0x2b, 0xbe, 0x84,
	0x63, 0xe1, 0xca, 0x44, 0x6f, 0x96, 0x54, 0xfb, 0x08, 0x6a, 0xec, 0xdb, 0x66, 0x49, 0xf8, 0x1a,
	0xfc, 0xcc, 0x19, 0x09, 0xa2, 0x17, 0x4d, 0xed, 0xc6, 0x95, 0xc5, 0x7e, 0x26, 0x30, 0x02, 0x7f,
	0xee, 0x2e, 0x21, 0x88, 0x58, 0x73, 0xe0, 0xae, 0xfd, 0xd8, 0x9f, 0x8b, 0xe8, 0xb7, 0x0f, 0x27,
	0x53, 0xcb, 0x9c, 0xd6, 0x4c, 0xfc, 0x04, 0xc7, 0x0e, 0x71, 0x41, 0xc2, 0xb3, 0xa6, 0xd4, 0x2e,
	0x60, 0x67, 0xcf, 0x9b, 0x67, 0x7b, 0xb1, 0x61, 0x0f, 0xf0, 0x2b, 0xf4, 0x63, 0xd2, 0x2b, 0x59,
	0x4e, 0x52, 0x3d, 0x5b, 0x90, 0xc2, 0xff, 0x4f, 0x1c, 0x14, 0x7c, 0xe3, 0xe1, 0x47, 0x08, 0xae,
	0x79, 0xa5, 0xc8, 0x99, 0xbc, 0x6b, 0x6f, 0x97, 0xb7, 0xc3, 0xf6, 0x26, 0xd0, 0xbf, 0x9a, 0xe9,
	0xdd, 0xbd, 0xe0, 0xf9, 0xfd, 0x13, 0x36, 0xe2, 0x07, 0xe5, 0x6e, 0xbb, 0xf6, 0xa7, 0x7c, 0xfb,
	0x27, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x99, 0x97, 0x06, 0xad, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServerServicesClient is the client API for ServerServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerServicesClient interface {
	ServerConfig(ctx context.Context, in *ConfigInfo, opts ...grpc.CallOption) (*StringMessage, error)
	ReturnMatches(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (ServerServices_ReturnMatchesClient, error)
	CloseServer(ctx context.Context, in *IntMessage, opts ...grpc.CallOption) (*StringMessage, error)
	ActMembership(ctx context.Context, in *StringArray, opts ...grpc.CallOption) (*StringMessage, error)
}

type serverServicesClient struct {
	cc *grpc.ClientConn
}

func NewServerServicesClient(cc *grpc.ClientConn) ServerServicesClient {
	return &serverServicesClient{cc}
}

func (c *serverServicesClient) ServerConfig(ctx context.Context, in *ConfigInfo, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/serverservices.ServerServices/ServerConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverServicesClient) ReturnMatches(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (ServerServices_ReturnMatchesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ServerServices_serviceDesc.Streams[0], "/serverservices.ServerServices/ReturnMatches", opts...)
	if err != nil {
		return nil, err
	}
	x := &serverServicesReturnMatchesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ServerServices_ReturnMatchesClient interface {
	Recv() (*StringMessage, error)
	grpc.ClientStream
}

type serverServicesReturnMatchesClient struct {
	grpc.ClientStream
}

func (x *serverServicesReturnMatchesClient) Recv() (*StringMessage, error) {
	m := new(StringMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serverServicesClient) CloseServer(ctx context.Context, in *IntMessage, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/serverservices.ServerServices/CloseServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverServicesClient) ActMembership(ctx context.Context, in *StringArray, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/serverservices.ServerServices/ActMembership", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerServicesServer is the server API for ServerServices service.
type ServerServicesServer interface {
	ServerConfig(context.Context, *ConfigInfo) (*StringMessage, error)
	ReturnMatches(*StringMessage, ServerServices_ReturnMatchesServer) error
	CloseServer(context.Context, *IntMessage) (*StringMessage, error)
	ActMembership(context.Context, *StringArray) (*StringMessage, error)
}

func RegisterServerServicesServer(s *grpc.Server, srv ServerServicesServer) {
	s.RegisterService(&_ServerServices_serviceDesc, srv)
}

func _ServerServices_ServerConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServicesServer).ServerConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverservices.ServerServices/ServerConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServicesServer).ServerConfig(ctx, req.(*ConfigInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerServices_ReturnMatches_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StringMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServerServicesServer).ReturnMatches(m, &serverServicesReturnMatchesServer{stream})
}

type ServerServices_ReturnMatchesServer interface {
	Send(*StringMessage) error
	grpc.ServerStream
}

type serverServicesReturnMatchesServer struct {
	grpc.ServerStream
}

func (x *serverServicesReturnMatchesServer) Send(m *StringMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _ServerServices_CloseServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServicesServer).CloseServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverservices.ServerServices/CloseServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServicesServer).CloseServer(ctx, req.(*IntMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerServices_ActMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringArray)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServicesServer).ActMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverservices.ServerServices/ActMembership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServicesServer).ActMembership(ctx, req.(*StringArray))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServerServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serverservices.ServerServices",
	HandlerType: (*ServerServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServerConfig",
			Handler:    _ServerServices_ServerConfig_Handler,
		},
		{
			MethodName: "CloseServer",
			Handler:    _ServerServices_CloseServer_Handler,
		},
		{
			MethodName: "ActMembership",
			Handler:    _ServerServices_ActMembership_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReturnMatches",
			Handler:       _ServerServices_ReturnMatches_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "server_services.proto",
}
