// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server_services.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConfigInfo struct {
	LogLevel             int32    `protobuf:"varint,1,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	VmIndex              int32    `protobuf:"varint,2,opt,name=vm_index,json=vmIndex,proto3" json:"vm_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigInfo) Reset()         { *m = ConfigInfo{} }
func (m *ConfigInfo) String() string { return proto.CompactTextString(m) }
func (*ConfigInfo) ProtoMessage()    {}
func (*ConfigInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8065473b34526ba4, []int{0}
}

func (m *ConfigInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigInfo.Unmarshal(m, b)
}
func (m *ConfigInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigInfo.Marshal(b, m, deterministic)
}
func (m *ConfigInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigInfo.Merge(m, src)
}
func (m *ConfigInfo) XXX_Size() int {
	return xxx_messageInfo_ConfigInfo.Size(m)
}
func (m *ConfigInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigInfo proto.InternalMessageInfo

func (m *ConfigInfo) GetLogLevel() int32 {
	if m != nil {
		return m.LogLevel
	}
	return 0
}

func (m *ConfigInfo) GetVmIndex() int32 {
	if m != nil {
		return m.VmIndex
	}
	return 0
}

type StringMessage struct {
	Mesg                 string   `protobuf:"bytes,1,opt,name=mesg,proto3" json:"mesg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringMessage) Reset()         { *m = StringMessage{} }
func (m *StringMessage) String() string { return proto.CompactTextString(m) }
func (*StringMessage) ProtoMessage()    {}
func (*StringMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8065473b34526ba4, []int{1}
}

func (m *StringMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMessage.Unmarshal(m, b)
}
func (m *StringMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMessage.Marshal(b, m, deterministic)
}
func (m *StringMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMessage.Merge(m, src)
}
func (m *StringMessage) XXX_Size() int {
	return xxx_messageInfo_StringMessage.Size(m)
}
func (m *StringMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StringMessage proto.InternalMessageInfo

func (m *StringMessage) GetMesg() string {
	if m != nil {
		return m.Mesg
	}
	return ""
}

type StringArray struct {
	Mesgs                []string `protobuf:"bytes,1,rep,name=mesgs,proto3" json:"mesgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringArray) Reset()         { *m = StringArray{} }
func (m *StringArray) String() string { return proto.CompactTextString(m) }
func (*StringArray) ProtoMessage()    {}
func (*StringArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_8065473b34526ba4, []int{2}
}

func (m *StringArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringArray.Unmarshal(m, b)
}
func (m *StringArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringArray.Marshal(b, m, deterministic)
}
func (m *StringArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringArray.Merge(m, src)
}
func (m *StringArray) XXX_Size() int {
	return xxx_messageInfo_StringArray.Size(m)
}
func (m *StringArray) XXX_DiscardUnknown() {
	xxx_messageInfo_StringArray.DiscardUnknown(m)
}

var xxx_messageInfo_StringArray proto.InternalMessageInfo

func (m *StringArray) GetMesgs() []string {
	if m != nil {
		return m.Mesgs
	}
	return nil
}

type IntMessage struct {
	Mesg                 int32    `protobuf:"varint,1,opt,name=mesg,proto3" json:"mesg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntMessage) Reset()         { *m = IntMessage{} }
func (m *IntMessage) String() string { return proto.CompactTextString(m) }
func (*IntMessage) ProtoMessage()    {}
func (*IntMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8065473b34526ba4, []int{3}
}

func (m *IntMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntMessage.Unmarshal(m, b)
}
func (m *IntMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntMessage.Marshal(b, m, deterministic)
}
func (m *IntMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntMessage.Merge(m, src)
}
func (m *IntMessage) XXX_Size() int {
	return xxx_messageInfo_IntMessage.Size(m)
}
func (m *IntMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_IntMessage.DiscardUnknown(m)
}

var xxx_messageInfo_IntMessage proto.InternalMessageInfo

func (m *IntMessage) GetMesg() int32 {
	if m != nil {
		return m.Mesg
	}
	return 0
}

type DetectorMessage struct {
	Header               string   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	SessNum              int32    `protobuf:"varint,3,opt,name=sess_num,json=sessNum,proto3" json:"sess_num,omitempty"`
	Ttl                  int32    `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	NodeId               int32    `protobuf:"varint,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetectorMessage) Reset()         { *m = DetectorMessage{} }
func (m *DetectorMessage) String() string { return proto.CompactTextString(m) }
func (*DetectorMessage) ProtoMessage()    {}
func (*DetectorMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8065473b34526ba4, []int{4}
}

func (m *DetectorMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectorMessage.Unmarshal(m, b)
}
func (m *DetectorMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectorMessage.Marshal(b, m, deterministic)
}
func (m *DetectorMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectorMessage.Merge(m, src)
}
func (m *DetectorMessage) XXX_Size() int {
	return xxx_messageInfo_DetectorMessage.Size(m)
}
func (m *DetectorMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectorMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DetectorMessage proto.InternalMessageInfo

func (m *DetectorMessage) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *DetectorMessage) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *DetectorMessage) GetSessNum() int32 {
	if m != nil {
		return m.SessNum
	}
	return 0
}

func (m *DetectorMessage) GetTtl() int32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func (m *DetectorMessage) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

type Member struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	SessNum              int32    `protobuf:"varint,2,opt,name=sess_num,json=sessNum,proto3" json:"sess_num,omitempty"`
	NodeId               int32    `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_8065473b34526ba4, []int{5}
}

func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Member) GetSessNum() int32 {
	if m != nil {
		return m.SessNum
	}
	return 0
}

func (m *Member) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

type FullMembershipList struct {
	List                 []*Member `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FullMembershipList) Reset()         { *m = FullMembershipList{} }
func (m *FullMembershipList) String() string { return proto.CompactTextString(m) }
func (*FullMembershipList) ProtoMessage()    {}
func (*FullMembershipList) Descriptor() ([]byte, []int) {
	return fileDescriptor_8065473b34526ba4, []int{6}
}

func (m *FullMembershipList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FullMembershipList.Unmarshal(m, b)
}
func (m *FullMembershipList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FullMembershipList.Marshal(b, m, deterministic)
}
func (m *FullMembershipList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FullMembershipList.Merge(m, src)
}
func (m *FullMembershipList) XXX_Size() int {
	return xxx_messageInfo_FullMembershipList.Size(m)
}
func (m *FullMembershipList) XXX_DiscardUnknown() {
	xxx_messageInfo_FullMembershipList.DiscardUnknown(m)
}

var xxx_messageInfo_FullMembershipList proto.InternalMessageInfo

func (m *FullMembershipList) GetList() []*Member {
	if m != nil {
		return m.List
	}
	return nil
}

type UDPMessage struct {
	MessageType          string              `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Dm                   *DetectorMessage    `protobuf:"bytes,2,opt,name=dm,proto3" json:"dm,omitempty"`
	Fm                   *FullMembershipList `protobuf:"bytes,3,opt,name=fm,proto3" json:"fm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UDPMessage) Reset()         { *m = UDPMessage{} }
func (m *UDPMessage) String() string { return proto.CompactTextString(m) }
func (*UDPMessage) ProtoMessage()    {}
func (*UDPMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8065473b34526ba4, []int{7}
}

func (m *UDPMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UDPMessage.Unmarshal(m, b)
}
func (m *UDPMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UDPMessage.Marshal(b, m, deterministic)
}
func (m *UDPMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UDPMessage.Merge(m, src)
}
func (m *UDPMessage) XXX_Size() int {
	return xxx_messageInfo_UDPMessage.Size(m)
}
func (m *UDPMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UDPMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UDPMessage proto.InternalMessageInfo

func (m *UDPMessage) GetMessageType() string {
	if m != nil {
		return m.MessageType
	}
	return ""
}

func (m *UDPMessage) GetDm() *DetectorMessage {
	if m != nil {
		return m.Dm
	}
	return nil
}

func (m *UDPMessage) GetFm() *FullMembershipList {
	if m != nil {
		return m.Fm
	}
	return nil
}

// SDFS related messages
type FileCfg struct {
	RemoteFilepath       string   `protobuf:"bytes,1,opt,name=remote_filepath,json=remoteFilepath,proto3" json:"remote_filepath,omitempty"`
	RepNumber            int32    `protobuf:"varint,2,opt,name=rep_number,json=repNumber,proto3" json:"rep_number,omitempty"`
	FileVersion          int32    `protobuf:"varint,3,opt,name=file_version,json=fileVersion,proto3" json:"file_version,omitempty"`
	IgnoreMemtable       bool     `protobuf:"varint,4,opt,name=ignore_memtable,json=ignoreMemtable,proto3" json:"ignore_memtable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileCfg) Reset()         { *m = FileCfg{} }
func (m *FileCfg) String() string { return proto.CompactTextString(m) }
func (*FileCfg) ProtoMessage()    {}
func (*FileCfg) Descriptor() ([]byte, []int) {
	return fileDescriptor_8065473b34526ba4, []int{8}
}

func (m *FileCfg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileCfg.Unmarshal(m, b)
}
func (m *FileCfg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileCfg.Marshal(b, m, deterministic)
}
func (m *FileCfg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileCfg.Merge(m, src)
}
func (m *FileCfg) XXX_Size() int {
	return xxx_messageInfo_FileCfg.Size(m)
}
func (m *FileCfg) XXX_DiscardUnknown() {
	xxx_messageInfo_FileCfg.DiscardUnknown(m)
}

var xxx_messageInfo_FileCfg proto.InternalMessageInfo

func (m *FileCfg) GetRemoteFilepath() string {
	if m != nil {
		return m.RemoteFilepath
	}
	return ""
}

func (m *FileCfg) GetRepNumber() int32 {
	if m != nil {
		return m.RepNumber
	}
	return 0
}

func (m *FileCfg) GetFileVersion() int32 {
	if m != nil {
		return m.FileVersion
	}
	return 0
}

func (m *FileCfg) GetIgnoreMemtable() bool {
	if m != nil {
		return m.IgnoreMemtable
	}
	return false
}

type FileTransMessage struct {
	// Types that are valid to be assigned to Message:
	//	*FileTransMessage_Chunk
	//	*FileTransMessage_Config
	Message              isFileTransMessage_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *FileTransMessage) Reset()         { *m = FileTransMessage{} }
func (m *FileTransMessage) String() string { return proto.CompactTextString(m) }
func (*FileTransMessage) ProtoMessage()    {}
func (*FileTransMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8065473b34526ba4, []int{9}
}

func (m *FileTransMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileTransMessage.Unmarshal(m, b)
}
func (m *FileTransMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileTransMessage.Marshal(b, m, deterministic)
}
func (m *FileTransMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileTransMessage.Merge(m, src)
}
func (m *FileTransMessage) XXX_Size() int {
	return xxx_messageInfo_FileTransMessage.Size(m)
}
func (m *FileTransMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FileTransMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FileTransMessage proto.InternalMessageInfo

type isFileTransMessage_Message interface {
	isFileTransMessage_Message()
}

type FileTransMessage_Chunk struct {
	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3,oneof"`
}

type FileTransMessage_Config struct {
	Config *FileCfg `protobuf:"bytes,2,opt,name=config,proto3,oneof"`
}

func (*FileTransMessage_Chunk) isFileTransMessage_Message() {}

func (*FileTransMessage_Config) isFileTransMessage_Message() {}

func (m *FileTransMessage) GetMessage() isFileTransMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *FileTransMessage) GetChunk() []byte {
	if x, ok := m.GetMessage().(*FileTransMessage_Chunk); ok {
		return x.Chunk
	}
	return nil
}

func (m *FileTransMessage) GetConfig() *FileCfg {
	if x, ok := m.GetMessage().(*FileTransMessage_Config); ok {
		return x.Config
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*FileTransMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _FileTransMessage_OneofMarshaler, _FileTransMessage_OneofUnmarshaler, _FileTransMessage_OneofSizer, []interface{}{
		(*FileTransMessage_Chunk)(nil),
		(*FileTransMessage_Config)(nil),
	}
}

func _FileTransMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*FileTransMessage)
	// message
	switch x := m.Message.(type) {
	case *FileTransMessage_Chunk:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.Chunk)
	case *FileTransMessage_Config:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Config); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("FileTransMessage.Message has unexpected type %T", x)
	}
	return nil
}

func _FileTransMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*FileTransMessage)
	switch tag {
	case 1: // message.chunk
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Message = &FileTransMessage_Chunk{x}
		return true, err
	case 2: // message.config
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FileCfg)
		err := b.DecodeMessage(msg)
		m.Message = &FileTransMessage_Config{msg}
		return true, err
	default:
		return false, nil
	}
}

func _FileTransMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*FileTransMessage)
	// message
	switch x := m.Message.(type) {
	case *FileTransMessage_Chunk:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Chunk)))
		n += len(x.Chunk)
	case *FileTransMessage_Config:
		s := proto.Size(x.Config)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// For pull file
type PullFileInfo struct {
	FileName  string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	NumOfFile int32  `protobuf:"varint,2,opt,name=num_of_file,json=numOfFile,proto3" json:"num_of_file,omitempty"`
	MyID      int32  `protobuf:"varint,3,opt,name=myID,proto3" json:"myID,omitempty"`
	// input config
	IgnoreMemtable bool  `protobuf:"varint,4,opt,name=ignore_memtable,json=ignoreMemtable,proto3" json:"ignore_memtable,omitempty"`
	FetchKey       int32 `protobuf:"varint,5,opt,name=fetch_key,json=fetchKey,proto3" json:"fetch_key,omitempty"`
	// type 0: PullOneFile, type 1: PullAllKey, type 2: query existence
	FetchType int32 `protobuf:"varint,6,opt,name=fetch_type,json=fetchType,proto3" json:"fetch_type,omitempty"`
	// returned values
	FileExist            bool     `protobuf:"varint,8,opt,name=file_exist,json=fileExist,proto3" json:"file_exist,omitempty"`
	LatestVersion        int32    `protobuf:"varint,9,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullFileInfo) Reset()         { *m = PullFileInfo{} }
func (m *PullFileInfo) String() string { return proto.CompactTextString(m) }
func (*PullFileInfo) ProtoMessage()    {}
func (*PullFileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8065473b34526ba4, []int{10}
}

func (m *PullFileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullFileInfo.Unmarshal(m, b)
}
func (m *PullFileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullFileInfo.Marshal(b, m, deterministic)
}
func (m *PullFileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullFileInfo.Merge(m, src)
}
func (m *PullFileInfo) XXX_Size() int {
	return xxx_messageInfo_PullFileInfo.Size(m)
}
func (m *PullFileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PullFileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PullFileInfo proto.InternalMessageInfo

func (m *PullFileInfo) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *PullFileInfo) GetNumOfFile() int32 {
	if m != nil {
		return m.NumOfFile
	}
	return 0
}

func (m *PullFileInfo) GetMyID() int32 {
	if m != nil {
		return m.MyID
	}
	return 0
}

func (m *PullFileInfo) GetIgnoreMemtable() bool {
	if m != nil {
		return m.IgnoreMemtable
	}
	return false
}

func (m *PullFileInfo) GetFetchKey() int32 {
	if m != nil {
		return m.FetchKey
	}
	return 0
}

func (m *PullFileInfo) GetFetchType() int32 {
	if m != nil {
		return m.FetchType
	}
	return 0
}

func (m *PullFileInfo) GetFileExist() bool {
	if m != nil {
		return m.FileExist
	}
	return false
}

func (m *PullFileInfo) GetLatestVersion() int32 {
	if m != nil {
		return m.LatestVersion
	}
	return 0
}

func init() {
	proto.RegisterType((*ConfigInfo)(nil), "pb.ConfigInfo")
	proto.RegisterType((*StringMessage)(nil), "pb.StringMessage")
	proto.RegisterType((*StringArray)(nil), "pb.StringArray")
	proto.RegisterType((*IntMessage)(nil), "pb.IntMessage")
	proto.RegisterType((*DetectorMessage)(nil), "pb.DetectorMessage")
	proto.RegisterType((*Member)(nil), "pb.Member")
	proto.RegisterType((*FullMembershipList)(nil), "pb.FullMembershipList")
	proto.RegisterType((*UDPMessage)(nil), "pb.UDPMessage")
	proto.RegisterType((*FileCfg)(nil), "pb.FileCfg")
	proto.RegisterType((*FileTransMessage)(nil), "pb.FileTransMessage")
	proto.RegisterType((*PullFileInfo)(nil), "pb.PullFileInfo")
}

func init() { proto.RegisterFile("server_services.proto", fileDescriptor_8065473b34526ba4) }

var fileDescriptor_8065473b34526ba4 = []byte{
	// 792 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x4d, 0x8f, 0xe3, 0x44,
	0x10, 0x8d, 0x3d, 0x93, 0x0f, 0x97, 0x93, 0xcc, 0xd0, 0x2c, 0x4b, 0x18, 0xc4, 0x6a, 0xf0, 0x68,
	0x61, 0x4e, 0x11, 0x9b, 0x05, 0x21, 0x8e, 0x4b, 0xc2, 0x68, 0x23, 0x36, 0x43, 0xe4, 0x2c, 0x9c,
	0x90, 0x2c, 0x27, 0x2e, 0x3b, 0xd6, 0x76, 0xdb, 0x56, 0x77, 0x3b, 0xda, 0x48, 0xdc, 0xb8, 0x71,
	0xe1, 0x17, 0xf0, 0x03, 0xf9, 0x17, 0xa8, 0x3f, 0xb2, 0xc9, 0x4c, 0x06, 0x69, 0x4e, 0xe9, 0x7a,
	0x2e, 0xd7, 0xab, 0x7a, 0xfd, 0x5c, 0x81, 0x4f, 0x04, 0xf2, 0x0d, 0xf2, 0x48, 0xfd, 0xe4, 0x2b,
	0x14, 0xc3, 0x8a, 0x97, 0xb2, 0x24, 0x6e, 0xb5, 0x0c, 0x26, 0x00, 0xe3, 0xb2, 0x48, 0xf3, 0x6c,
	0x5a, 0xa4, 0x25, 0xf9, 0x1c, 0x3c, 0x5a, 0x66, 0x11, 0xc5, 0x0d, 0xd2, 0x81, 0x73, 0xe9, 0x5c,
	0x37, 0xc3, 0x0e, 0x2d, 0xb3, 0x37, 0x2a, 0x26, 0x9f, 0x41, 0x67, 0xc3, 0xa2, 0xbc, 0x48, 0xf0,
	0xfd, 0xc0, 0xd5, 0xcf, 0xda, 0x1b, 0x36, 0x55, 0x61, 0x70, 0x05, 0xbd, 0x85, 0xe4, 0x79, 0x91,
	0xcd, 0x50, 0x88, 0x38, 0x43, 0x42, 0xe0, 0x94, 0xa1, 0xc8, 0x74, 0x0d, 0x2f, 0xd4, 0xe7, 0xe0,
	0x0a, 0x7c, 0x93, 0xf4, 0x8a, 0xf3, 0x78, 0x4b, 0x9e, 0x40, 0x53, 0xc1, 0x62, 0xe0, 0x5c, 0x9e,
	0x5c, 0x7b, 0xa1, 0x09, 0x82, 0x4b, 0x80, 0x69, 0x21, 0x1f, 0x2a, 0xd3, 0xb4, 0x65, 0xfe, 0x74,
	0xe0, 0x6c, 0x82, 0x12, 0x57, 0xb2, 0xe4, 0xbb, 0xbc, 0xa7, 0xd0, 0x5a, 0x63, 0x9c, 0x20, 0xb7,
	0x84, 0x36, 0x52, 0xef, 0xc7, 0x49, 0xc2, 0x75, 0xbb, 0x5e, 0xa8, 0xcf, 0x6a, 0x0c, 0x81, 0x42,
	0x44, 0x45, 0xcd, 0x06, 0x27, 0x66, 0x0c, 0x15, 0xdf, 0xd6, 0x8c, 0x9c, 0xc3, 0x89, 0x94, 0x74,
	0x70, 0xaa, 0x51, 0x75, 0x24, 0x9f, 0x42, 0xbb, 0x28, 0x13, 0x8c, 0xf2, 0x64, 0xd0, 0xd4, 0x68,
	0x4b, 0x85, 0xd3, 0x24, 0x98, 0x43, 0x6b, 0x86, 0x6c, 0x79, 0xc0, 0xe1, 0xfc, 0x0f, 0x87, 0x7b,
	0x97, 0xe3, 0xa0, 0xe2, 0xc9, 0x9d, 0x8a, 0xdf, 0x02, 0xb9, 0xa9, 0x29, 0x35, 0x55, 0xc5, 0x3a,
	0xaf, 0xde, 0xe4, 0x42, 0x92, 0x67, 0x70, 0x4a, 0x73, 0x21, 0xb5, 0x48, 0xfe, 0x08, 0x86, 0xd5,
	0x72, 0x68, 0x32, 0x42, 0x8d, 0x07, 0x7f, 0x00, 0xfc, 0x3a, 0x99, 0xef, 0x74, 0xf8, 0x12, 0xba,
	0xcc, 0x1c, 0x23, 0xb9, 0xad, 0xd0, 0xf6, 0xe4, 0x5b, 0xec, 0xed, 0xb6, 0x42, 0x72, 0x05, 0x6e,
	0x62, 0x9a, 0xf2, 0x47, 0x1f, 0xab, 0x72, 0xf7, 0xb4, 0x0c, 0xdd, 0x84, 0x91, 0xaf, 0xc0, 0x4d,
	0x8d, 0x3a, 0xfe, 0xe8, 0xa9, 0x4a, 0x3a, 0xee, 0x2c, 0x74, 0x53, 0x16, 0xfc, 0xe3, 0x40, 0xfb,
	0x26, 0xa7, 0x38, 0x4e, 0x33, 0xf2, 0x35, 0x9c, 0x71, 0x64, 0xa5, 0xc4, 0x28, 0xcd, 0x29, 0x56,
	0xb1, 0x5c, 0x5b, 0xfa, 0xbe, 0x81, 0x6f, 0x2c, 0x4a, 0xbe, 0x00, 0xe0, 0x58, 0x29, 0x6d, 0x96,
	0xc8, 0xad, 0x3c, 0x1e, 0xc7, 0xea, 0x56, 0x03, 0x6a, 0x06, 0x55, 0x20, 0xda, 0x20, 0x17, 0x79,
	0x59, 0x58, 0x95, 0x7c, 0x85, 0xfd, 0x66, 0x20, 0x45, 0x95, 0x67, 0x45, 0xc9, 0x31, 0x62, 0xc8,
	0x64, 0xbc, 0xa4, 0xa8, 0xef, 0xac, 0x13, 0xf6, 0x0d, 0x3c, 0xb3, 0x68, 0xf0, 0x3b, 0x9c, 0x2b,
	0xda, 0xb7, 0x3c, 0x2e, 0xc4, 0xde, 0x2b, 0xcd, 0xd5, 0xba, 0x2e, 0xde, 0xe9, 0xee, 0xba, 0xaf,
	0x1b, 0xa1, 0x09, 0xc9, 0x73, 0x68, 0xad, 0xf4, 0x97, 0x60, 0xc5, 0xf1, 0xf5, 0xdc, 0x66, 0xb8,
	0xd7, 0x8d, 0xd0, 0x3e, 0xfc, 0xd1, 0x83, 0xb6, 0x95, 0x33, 0xf8, 0xcb, 0x85, 0xee, 0xbc, 0xa6,
	0x54, 0x25, 0xed, 0x3e, 0x1f, 0xdd, 0x7a, 0x11, 0xb3, 0x9d, 0xf6, 0x1d, 0x05, 0xdc, 0xc6, 0x0c,
	0xc9, 0x33, 0xf0, 0x8b, 0x9a, 0x45, 0x65, 0xaa, 0xf5, 0xd9, 0xcd, 0x5d, 0xd4, 0xec, 0x97, 0x54,
	0x15, 0xd0, 0x5e, 0xdf, 0x4e, 0x27, 0x76, 0x5e, 0x7d, 0x7e, 0xf4, 0xa0, 0x9a, 0x19, 0xe5, 0x6a,
	0x1d, 0xbd, 0xc3, 0xad, 0x75, 0x6a, 0x47, 0x03, 0x3f, 0xe3, 0x56, 0x09, 0x6e, 0x1e, 0x6a, 0x4f,
	0xb4, 0x0c, 0xb1, 0x46, 0xb4, 0x23, 0xd4, 0x63, 0xd5, 0x35, 0xbe, 0x57, 0x46, 0xeb, 0xe8, 0xfa,
	0x7a, 0x8e, 0x9f, 0x14, 0x40, 0x9e, 0x43, 0x9f, 0xc6, 0x12, 0x85, 0xfc, 0x70, 0x23, 0x9e, 0xae,
	0xd0, 0x33, 0xa8, 0xbd, 0x93, 0xd1, 0xbf, 0x0e, 0xf4, 0x17, 0x7a, 0xcd, 0x2c, 0xec, 0x96, 0x21,
	0x2f, 0xa1, 0x6b, 0x10, 0xb3, 0x61, 0x48, 0x5f, 0x29, 0xba, 0xdf, 0x36, 0x17, 0x1f, 0xa9, 0xf8,
	0xce, 0xde, 0x08, 0x1a, 0xe4, 0x7b, 0xe8, 0x85, 0x28, 0x6b, 0x5e, 0xcc, 0x62, 0xb9, 0x5a, 0xa3,
	0x20, 0x67, 0xfb, 0x2c, 0xbd, 0x38, 0x1e, 0x7c, 0xed, 0x1b, 0x87, 0x8c, 0xc0, 0x1f, 0xd3, 0x52,
	0xa0, 0xa1, 0x34, 0x64, 0xfb, 0x55, 0xf2, 0x30, 0xd9, 0x77, 0xd0, 0x7b, 0xb5, 0x92, 0x7b, 0x63,
	0x3f, 0x8e, 0x6c, 0xf4, 0xb7, 0x0b, 0xdd, 0x45, 0x92, 0x8a, 0x0f, 0x93, 0x0e, 0xa1, 0xa3, 0xe2,
	0x71, 0x4c, 0xe9, 0x71, 0x89, 0xfb, 0x40, 0xd0, 0x20, 0x3f, 0x40, 0x4f, 0x7b, 0x32, 0x45, 0xae,
	0xee, 0x5e, 0x90, 0x27, 0x3b, 0xb3, 0x1d, 0x5a, 0xf5, 0xe2, 0xde, 0x0c, 0x41, 0xe3, 0xda, 0x21,
	0x2f, 0xc0, 0xdb, 0x79, 0x4e, 0x90, 0x73, 0x95, 0x70, 0x68, 0xc1, 0x8b, 0x23, 0x24, 0x68, 0x90,
	0x21, 0xb4, 0xe7, 0xb5, 0xd4, 0x26, 0x3b, 0x1e, 0xe7, 0x98, 0x84, 0xbc, 0x00, 0x98, 0x20, 0x45,
	0xf3, 0xc9, 0x3e, 0xea, 0x95, 0x65, 0x4b, 0xff, 0xa3, 0xbc, 0xfc, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0xfa, 0x76, 0xc7, 0x39, 0x6a, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServerServicesClient is the client API for ServerServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerServicesClient interface {
	ServerConfig(ctx context.Context, in *ConfigInfo, opts ...grpc.CallOption) (*StringMessage, error)
	ReturnMatches(ctx context.Context, in *StringArray, opts ...grpc.CallOption) (ServerServices_ReturnMatchesClient, error)
	CloseServer(ctx context.Context, in *IntMessage, opts ...grpc.CallOption) (*StringMessage, error)
	ActMembership(ctx context.Context, in *StringArray, opts ...grpc.CallOption) (*StringMessage, error)
}

type serverServicesClient struct {
	cc *grpc.ClientConn
}

func NewServerServicesClient(cc *grpc.ClientConn) ServerServicesClient {
	return &serverServicesClient{cc}
}

func (c *serverServicesClient) ServerConfig(ctx context.Context, in *ConfigInfo, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/pb.ServerServices/ServerConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverServicesClient) ReturnMatches(ctx context.Context, in *StringArray, opts ...grpc.CallOption) (ServerServices_ReturnMatchesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ServerServices_serviceDesc.Streams[0], "/pb.ServerServices/ReturnMatches", opts...)
	if err != nil {
		return nil, err
	}
	x := &serverServicesReturnMatchesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ServerServices_ReturnMatchesClient interface {
	Recv() (*StringMessage, error)
	grpc.ClientStream
}

type serverServicesReturnMatchesClient struct {
	grpc.ClientStream
}

func (x *serverServicesReturnMatchesClient) Recv() (*StringMessage, error) {
	m := new(StringMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serverServicesClient) CloseServer(ctx context.Context, in *IntMessage, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/pb.ServerServices/CloseServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverServicesClient) ActMembership(ctx context.Context, in *StringArray, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/pb.ServerServices/ActMembership", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerServicesServer is the server API for ServerServices service.
type ServerServicesServer interface {
	ServerConfig(context.Context, *ConfigInfo) (*StringMessage, error)
	ReturnMatches(*StringArray, ServerServices_ReturnMatchesServer) error
	CloseServer(context.Context, *IntMessage) (*StringMessage, error)
	ActMembership(context.Context, *StringArray) (*StringMessage, error)
}

func RegisterServerServicesServer(s *grpc.Server, srv ServerServicesServer) {
	s.RegisterService(&_ServerServices_serviceDesc, srv)
}

func _ServerServices_ServerConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServicesServer).ServerConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ServerServices/ServerConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServicesServer).ServerConfig(ctx, req.(*ConfigInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerServices_ReturnMatches_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StringArray)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServerServicesServer).ReturnMatches(m, &serverServicesReturnMatchesServer{stream})
}

type ServerServices_ReturnMatchesServer interface {
	Send(*StringMessage) error
	grpc.ServerStream
}

type serverServicesReturnMatchesServer struct {
	grpc.ServerStream
}

func (x *serverServicesReturnMatchesServer) Send(m *StringMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _ServerServices_CloseServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServicesServer).CloseServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ServerServices/CloseServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServicesServer).CloseServer(ctx, req.(*IntMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerServices_ActMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringArray)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServicesServer).ActMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ServerServices/ActMembership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServicesServer).ActMembership(ctx, req.(*StringArray))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServerServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ServerServices",
	HandlerType: (*ServerServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServerConfig",
			Handler:    _ServerServices_ServerConfig_Handler,
		},
		{
			MethodName: "CloseServer",
			Handler:    _ServerServices_CloseServer_Handler,
		},
		{
			MethodName: "ActMembership",
			Handler:    _ServerServices_ActMembership_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReturnMatches",
			Handler:       _ServerServices_ReturnMatches_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "server_services.proto",
}

// SdfsServicesClient is the client API for SdfsServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SdfsServicesClient interface {
	// SDFS client stub
	SdfsCall(ctx context.Context, in *StringArray, opts ...grpc.CallOption) (*StringArray, error)
	// SDFS related functions
	TransferFiles(ctx context.Context, opts ...grpc.CallOption) (SdfsServices_TransferFilesClient, error)
	PullFiles(ctx context.Context, in *PullFileInfo, opts ...grpc.CallOption) (*PullFileInfo, error)
	PutFile(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*IntMessage, error)
	DeleteFile(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*IntMessage, error)
}

type sdfsServicesClient struct {
	cc *grpc.ClientConn
}

func NewSdfsServicesClient(cc *grpc.ClientConn) SdfsServicesClient {
	return &sdfsServicesClient{cc}
}

func (c *sdfsServicesClient) SdfsCall(ctx context.Context, in *StringArray, opts ...grpc.CallOption) (*StringArray, error) {
	out := new(StringArray)
	err := c.cc.Invoke(ctx, "/pb.SdfsServices/SdfsCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdfsServicesClient) TransferFiles(ctx context.Context, opts ...grpc.CallOption) (SdfsServices_TransferFilesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SdfsServices_serviceDesc.Streams[0], "/pb.SdfsServices/TransferFiles", opts...)
	if err != nil {
		return nil, err
	}
	x := &sdfsServicesTransferFilesClient{stream}
	return x, nil
}

type SdfsServices_TransferFilesClient interface {
	Send(*FileTransMessage) error
	CloseAndRecv() (*IntMessage, error)
	grpc.ClientStream
}

type sdfsServicesTransferFilesClient struct {
	grpc.ClientStream
}

func (x *sdfsServicesTransferFilesClient) Send(m *FileTransMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sdfsServicesTransferFilesClient) CloseAndRecv() (*IntMessage, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(IntMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sdfsServicesClient) PullFiles(ctx context.Context, in *PullFileInfo, opts ...grpc.CallOption) (*PullFileInfo, error) {
	out := new(PullFileInfo)
	err := c.cc.Invoke(ctx, "/pb.SdfsServices/PullFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdfsServicesClient) PutFile(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*IntMessage, error) {
	out := new(IntMessage)
	err := c.cc.Invoke(ctx, "/pb.SdfsServices/PutFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdfsServicesClient) DeleteFile(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*IntMessage, error) {
	out := new(IntMessage)
	err := c.cc.Invoke(ctx, "/pb.SdfsServices/DeleteFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SdfsServicesServer is the server API for SdfsServices service.
type SdfsServicesServer interface {
	// SDFS client stub
	SdfsCall(context.Context, *StringArray) (*StringArray, error)
	// SDFS related functions
	TransferFiles(SdfsServices_TransferFilesServer) error
	PullFiles(context.Context, *PullFileInfo) (*PullFileInfo, error)
	PutFile(context.Context, *StringMessage) (*IntMessage, error)
	DeleteFile(context.Context, *StringMessage) (*IntMessage, error)
}

func RegisterSdfsServicesServer(s *grpc.Server, srv SdfsServicesServer) {
	s.RegisterService(&_SdfsServices_serviceDesc, srv)
}

func _SdfsServices_SdfsCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringArray)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdfsServicesServer).SdfsCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SdfsServices/SdfsCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdfsServicesServer).SdfsCall(ctx, req.(*StringArray))
	}
	return interceptor(ctx, in, info, handler)
}

func _SdfsServices_TransferFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SdfsServicesServer).TransferFiles(&sdfsServicesTransferFilesServer{stream})
}

type SdfsServices_TransferFilesServer interface {
	SendAndClose(*IntMessage) error
	Recv() (*FileTransMessage, error)
	grpc.ServerStream
}

type sdfsServicesTransferFilesServer struct {
	grpc.ServerStream
}

func (x *sdfsServicesTransferFilesServer) SendAndClose(m *IntMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sdfsServicesTransferFilesServer) Recv() (*FileTransMessage, error) {
	m := new(FileTransMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SdfsServices_PullFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullFileInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdfsServicesServer).PullFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SdfsServices/PullFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdfsServicesServer).PullFiles(ctx, req.(*PullFileInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _SdfsServices_PutFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdfsServicesServer).PutFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SdfsServices/PutFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdfsServicesServer).PutFile(ctx, req.(*StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _SdfsServices_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdfsServicesServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SdfsServices/DeleteFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdfsServicesServer).DeleteFile(ctx, req.(*StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _SdfsServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SdfsServices",
	HandlerType: (*SdfsServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SdfsCall",
			Handler:    _SdfsServices_SdfsCall_Handler,
		},
		{
			MethodName: "PullFiles",
			Handler:    _SdfsServices_PullFiles_Handler,
		},
		{
			MethodName: "PutFile",
			Handler:    _SdfsServices_PutFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _SdfsServices_DeleteFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransferFiles",
			Handler:       _SdfsServices_TransferFiles_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "server_services.proto",
}
