---
- hosts: cs425
  remote_user: szhu28
  tasks:
    - name: copy code to VMs
      synchronize:
        delete: yes
        src: "{{ item.source }}"
        dest: "{{ item.dest }}"
      with_items:
        - { source: '/mnt/data/shared/gmaildrive/workspace/fa18byclass/CS425/fa18cs425mp/src', dest: '/home/szhu28/go/src/fa18cs425mp/' }
        - { source: '/mnt/data/shared/gmaildrive/workspace/fa18byclass/CS425/fa18cs425mp/examples', dest: '/home/szhu28/go/src/fa18cs425mp/' }

    - name: copy config file to VMs
      synchronize:
        delete: yes
        src: /mnt/data/shared/gmaildrive/workspace/fa18byclass/CS425/fa18cs425mp/remotecfg.json
        dest: /home/szhu28/cfg.json

    - name: compile the source code
      command: go install fa18cs425mp/src/...
