---
- hosts: cs425
  remote_user: szhu28
  tasks:
  - name: copy shell code to VMs
    synchronize:
      delete: yes
      src: /mnt/data/shared/gmaildrive/workspace/fa18byclass/CS425/fa18cs425mp/ansible/roles/install_spark.sh
      dest: /home/szhu28/install_spark.sh

  - name: execute the shell code
    command: bash install_spark.sh
